name: CI

on:
    pull_request:
        branches:
            - feature/ci

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_USER: ${{ secrets.TESTDB_USER }}
                    MYSQL_PASSWORD: ${{ secrets.TESTDB_PASSWORD }}
                    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
                    MYSQL_DATABASE: ${{ secrets.MYSQL_SCHEMA }}
                ports:
                    - 3306

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Verify MySQL connection from host
              run: |
                  mysql --version
                  sudo apt-get install -y mysql-client
                  sudo service mysql start
                  mysql -uroot -p $MYSQL_ROOT_PASSWORD -e "CREATE DATABASE ${{ secrets.MYSQL_SCHEMA }}"
                  mysql -uroot -p $MYSQL_ROOT_PASSWORD -e "USE ${{ secrets.MYSQL_SCHEMA }}; ${{ secrets.CHECK_DATA }}"
                  mysql -uroot -p $MYSQL_ROOT_PASSWORD -e "USE ${{ secrets.MYSQL_SCHEMA }}; ${{ secrets.CREATE_TABLE }}"
                  mysql -uroot -p $MYSQL_ROOT_PASSWORD -e "USE ${{ secrets.MYSQL_SCHEMA }}; ${{ secrets.INSERT_DATA }}"
                  mysql -uroot -p $MYSQL_ROOT_PASSWORD -e "SHOW DATABASES"

            - name: Make .env file
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
                  envkey_MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
                  envkey_MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
                  envkey_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
                  envkey_MYSQL_SCHEMA: ${{ secrets.MYSQL_SCHEMA }}
                  envkey_APP_NAME: ${{ secrets.APP_NAME }}
                  envkey_APP_PORT: ${{ secrets.APP_PORT }}
                  envkey_APP_CORS_ORIGINS: ${{ secrets.APP_CORS_ORIGINS }}
                  envkey_APP_WEB_URL: ${{ secrets.APP_WEB_URL }}
                  file_name: .env.test

            - name: Restart MySQL service
              run: sudo service mysql restart

            - name: Install dependencies and run tests
              run: |
                  npm install
                  npm test
              env:
                  CI: true
                  MYSQL_DATABASE: ${{ secrets.MYSQL_SCHEMA }}
                  DB_USERNAME: $MYSQL_USER
                  DB_PASSWORD: $MYSQL_PASSWORD
                  DB_PORT: ${{ secrets.MYSQL_PORT }}

            - name: Handle failure
              uses: actions/github-script@v3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const ref = "${{ github.ref }}"
                      const pull_number = Number(ref.split("/")[2])
                      await github.pulls.createReview({
                        ...context.repo,
                        pull_number,
                        body: "테스트코드를 다시 확인해주세요.",
                        event: "REQUEST_CHANGES"
                      })
                      await github.pulls.update({
                        ...context.repo,
                        pull_number,
                        state: "closed"
                      })
              if: failure()
